fail_fast: true

repos:
  - repo: local
    hooks:
      - id: cargofmt
        name: cargofmt
        entry: cargo +nightly fmt --all -- --check --color always
        language: system
        types: [rust]
        pass_filenames: false
