[package]
name = "playground"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]

[workspace]
members = ["comprehensive-rust", "web-gcd", "mandelbrot", "quickreplace"]
