[package]
name = "playground"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls"] }
scraper = "0.23.1"
tempfile = "3.19.1"
thiserror = "2.0.12"
